# Generated by Django 5.1.3 on 2024-12-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='duration_type',
        ),
    ]
